services:
  postgres:
    image: postgres:15
    container_name: patron_postgres
    profiles:
      - postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: patron_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  patron-backend:
    image: skeptrune/patron-backend:latest
    container_name: patron_backend
    pull_policy: always
    env_file:
      - backend/.env
    environment:
      REDIS_URL: redis://patron_redis:6379
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
