/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authForgotPassword } from "../funcs/authForgotPassword.js";
import { authGetCurrentUser } from "../funcs/authGetCurrentUser.js";
import { authGoogleCallback } from "../funcs/authGoogleCallback.js";
import { authGoogleRedirect } from "../funcs/authGoogleRedirect.js";
import { authLogin } from "../funcs/authLogin.js";
import { authLogout } from "../funcs/authLogout.js";
import { authRegister } from "../funcs/authRegister.js";
import { authResetPassword } from "../funcs/authResetPassword.js";
import { authVerifyEmail } from "../funcs/authVerifyEmail.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * Forgot password
   */
  async forgotPassword(
    request: models.ForgotPasswordRequest,
    options?: RequestOptions,
  ): Promise<models.ForgotPasswordResponse> {
    return unwrapAsync(authForgotPassword(
      this,
      request,
      options,
    ));
  }

  /**
   * Google OAuth redirect
   */
  async googleRedirect(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authGoogleRedirect(
      this,
      options,
    ));
  }

  /**
   * Google OAuth callback
   */
  async googleCallback(
    request: operations.GoogleAuthCallbackRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authGoogleCallback(
      this,
      request,
      options,
    ));
  }

  /**
   * User login
   */
  async login(
    request: models.LoginRequest,
    options?: RequestOptions,
  ): Promise<models.LoginResponse> {
    return unwrapAsync(authLogin(
      this,
      request,
      options,
    ));
  }

  /**
   * Logout
   */
  async logout(
    options?: RequestOptions,
  ): Promise<models.LogoutResponse> {
    return unwrapAsync(authLogout(
      this,
      options,
    ));
  }

  /**
   * Get current user info
   */
  async getCurrentUser(
    options?: RequestOptions,
  ): Promise<models.UserInfoResponse> {
    return unwrapAsync(authGetCurrentUser(
      this,
      options,
    ));
  }

  /**
   * User registration
   */
  async register(
    request: models.RegisterRequest,
    options?: RequestOptions,
  ): Promise<models.RegisterResponse> {
    return unwrapAsync(authRegister(
      this,
      request,
      options,
    ));
  }

  /**
   * Reset password
   */
  async resetPassword(
    request: models.ResetPasswordRequest,
    options?: RequestOptions,
  ): Promise<models.ResetPasswordResponse> {
    return unwrapAsync(authResetPassword(
      this,
      request,
      options,
    ));
  }

  /**
   * Email verification
   */
  async verifyEmail(
    request: operations.VerifyEmailRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authVerifyEmail(
      this,
      request,
      options,
    ));
  }
}
