/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesDeleteFile } from "../funcs/filesDeleteFile.js";
import { filesGetFile } from "../funcs/filesGetFile.js";
import { filesListFiles } from "../funcs/filesListFiles.js";
import { filesServeFileCdn } from "../funcs/filesServeFileCdn.js";
import { filesUpdateFile } from "../funcs/filesUpdateFile.js";
import { filesUploadFile } from "../funcs/filesUploadFile.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Files extends ClientSDK {
  /**
   * Serve file content with user authentication
   *
   * @remarks
   * This endpoint is designed to be used to get file content with proper authentication.
   * It verifies user access to the file and returns the file content with proper cache headers.
   * The file content is streamed directly from S3 to minimize memory usage for large files.
   *
   * # Errors
   * Returns an error if file not found, access denied, or S3 operations fail.
   */
  async serveFileCdn(
    request: operations.ServeFileCdnRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(filesServeFileCdn(
      this,
      request,
      options,
    ));
  }

  /**
   * List user's files with cursor-based pagination
   *
   * @remarks
   * # Errors
   * Returns an error if database operations fail.
   */
  async listFiles(
    request?: operations.ListFilesRequest | undefined,
    options?: RequestOptions,
  ): Promise<Array<models.UserFileInfo>> {
    return unwrapAsync(filesListFiles(
      this,
      request,
      options,
    ));
  }

  /**
   * Upload a file
   *
   * @remarks
   * # Errors
   * Returns an error if file upload, database operations, or file system operations fail.
   */
  async uploadFile(
    request: models.FileUploadRequest,
    options?: RequestOptions,
  ): Promise<models.FileUploadResponse> {
    return unwrapAsync(filesUploadFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific file by ID
   *
   * @remarks
   * # Errors
   * Returns an error if database operations fail or file not found.
   */
  async getFile(
    request: operations.GetFileRequest,
    options?: RequestOptions,
  ): Promise<models.UserFileInfo> {
    return unwrapAsync(filesGetFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Update file metadata and properties
   *
   * @remarks
   * # Errors
   * Returns an error if validation fails, file not found, or database operations fail.
   */
  async updateFile(
    request: operations.UpdateFileRequest,
    options?: RequestOptions,
  ): Promise<models.UserFileInfo> {
    return unwrapAsync(filesUpdateFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Permanently delete a user file
   *
   * @remarks
   * # Errors
   * Returns an error if file not found, permission denied, or storage operations fail.
   */
  async deleteFile(
    request: operations.DeleteFileRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(filesDeleteFile(
      this,
      request,
      options,
    ));
  }
}
