/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { outrankProcessWebhook } from "../funcs/outrankProcessWebhook.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Outrank extends ClientSDK {
  /**
   * Process Outrank webhook
   *
   * @remarks
   * # Security
   * Validates Bearer token from Authorization header against OUTRANK_ACCESS_TOKEN environment variable
   *
   * # Errors
   * Returns 401 if access token is invalid or missing, 500 for processing errors
   */
  async processWebhook(
    security: operations.ProcessWebhookSecurity,
    request: models.OutrankWebhookPayload,
    options?: RequestOptions,
  ): Promise<models.OutrankWebhookResponse> {
    return unwrapAsync(outrankProcessWebhook(
      this,
      security,
      request,
      options,
    ));
  }
}
