/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postsCreate } from "../funcs/postsCreate.js";
import { postsDelete } from "../funcs/postsDelete.js";
import { postsGet } from "../funcs/postsGet.js";
import { postsList } from "../funcs/postsList.js";
import { postsUpdate } from "../funcs/postsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Posts extends ClientSDK {
  /**
   * List posts with cursor-based pagination and optional series filtering
   *
   * @remarks
   * # Errors
   * Returns error if posts database query fails, series filtering fails, or connection issues occur
   */
  async list(
    request?: operations.ListPostsRequest | undefined,
    options?: RequestOptions,
  ): Promise<Array<models.PostResponse>> {
    return unwrapAsync(postsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new post
   *
   * @remarks
   * # Errors
   * Returns error if series not found, access denied, slug/number conflict, or database error
   */
  async create(
    request: models.CreatePostRequest,
    options?: RequestOptions,
  ): Promise<models.PostResponse> {
    return unwrapAsync(postsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific post by ID with series ownership validation
   *
   * @remarks
   * # Errors
   * Returns error if post not found, series access denied, or database connection error
   */
  async get(
    request: operations.GetPostRequest,
    options?: RequestOptions,
  ): Promise<models.PostResponse> {
    return unwrapAsync(postsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a post
   *
   * @remarks
   * # Errors
   * Returns error if post not found, access denied, slug/number conflict, or database update error
   */
  async update(
    request: operations.UpdatePostRequest,
    options?: RequestOptions,
  ): Promise<models.PostResponse> {
    return unwrapAsync(postsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a post (soft delete) with series ownership validation
   *
   * @remarks
   * # Errors
   * Returns error if post not found, series access denied, or database deletion error
   */
  async delete(
    request: operations.DeletePostRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(postsDelete(
      this,
      request,
      options,
    ));
  }
}
