/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { seriesCreate } from "../funcs/seriesCreate.js";
import { seriesDelete } from "../funcs/seriesDelete.js";
import { seriesGet } from "../funcs/seriesGet.js";
import { seriesList } from "../funcs/seriesList.js";
import { seriesUpdate } from "../funcs/seriesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Series extends ClientSDK {
  /**
   * List user's series with cursor-based pagination
   *
   * @remarks
   * # Errors
   * Returns error if series database query fails or connection issues occur
   */
  async list(
    request?: operations.ListSeriesRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListSeriesResponse, { cursor: string }>> {
    return unwrapResultIterator(seriesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new series
   *
   * @remarks
   * # Errors
   * Returns error if series creation fails, slug conflict, or database error
   */
  async create(
    request: models.CreateSeriesRequest,
    options?: RequestOptions,
  ): Promise<models.SeriesResponse> {
    return unwrapAsync(seriesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific series by ID with user ownership validation
   *
   * @remarks
   * # Errors
   * Returns error if series not found, user access denied, or database connection error
   */
  async get(
    request: operations.GetSeriesRequest,
    options?: RequestOptions,
  ): Promise<models.SeriesResponse> {
    return unwrapAsync(seriesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a series
   *
   * @remarks
   * # Errors
   * Returns error if series not found, access denied, slug conflict, or database update error
   */
  async update(
    request: operations.UpdateSeriesRequest,
    options?: RequestOptions,
  ): Promise<models.SeriesResponse> {
    return unwrapAsync(seriesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a series (soft delete) with user ownership validation
   *
   * @remarks
   * # Errors
   * Returns error if series not found, user access denied, or database deletion error
   */
  async delete(
    request: operations.DeleteSeriesRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(seriesDelete(
      this,
      request,
      options,
    ));
  }
}
