workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    CelebAI Video Generation API:
        inputs:
            - location: openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/patron/ts-sdk/celeb-ai-video-generation-api
targets:
    patron-ts-sdk:
        target: typescript
        source: CelebAI Video Generation API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/patron/ts-sdk/celeb-ai-video-generation-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
    patronts:
        target: ""
        source: ""
