/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeletePostRequest = {
  /**
   * UUID of the post to delete
   */
  postId: string;
};

/** @internal */
export const DeletePostRequest$inboundSchema: z.ZodType<
  DeletePostRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  post_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "post_id": "postId",
  });
});

/** @internal */
export type DeletePostRequest$Outbound = {
  post_id: string;
};

/** @internal */
export const DeletePostRequest$outboundSchema: z.ZodType<
  DeletePostRequest$Outbound,
  z.ZodTypeDef,
  DeletePostRequest
> = z.object({
  postId: z.string(),
}).transform((v) => {
  return remap$(v, {
    postId: "post_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeletePostRequest$ {
  /** @deprecated use `DeletePostRequest$inboundSchema` instead. */
  export const inboundSchema = DeletePostRequest$inboundSchema;
  /** @deprecated use `DeletePostRequest$outboundSchema` instead. */
  export const outboundSchema = DeletePostRequest$outboundSchema;
  /** @deprecated use `DeletePostRequest$Outbound` instead. */
  export type Outbound = DeletePostRequest$Outbound;
}

export function deletePostRequestToJSON(
  deletePostRequest: DeletePostRequest,
): string {
  return JSON.stringify(
    DeletePostRequest$outboundSchema.parse(deletePostRequest),
  );
}

export function deletePostRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeletePostRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePostRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePostRequest' from JSON`,
  );
}
