/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteFileRequest = {
  /**
   * UUID of the file to permanently delete
   */
  fileId: string;
};

/** @internal */
export type DeleteFileRequest$Outbound = {
  file_id: string;
};

/** @internal */
export const DeleteFileRequest$outboundSchema: z.ZodType<
  DeleteFileRequest$Outbound,
  z.ZodTypeDef,
  DeleteFileRequest
> = z.object({
  fileId: z.string(),
}).transform((v) => {
  return remap$(v, {
    fileId: "file_id",
  });
});

export function deleteFileRequestToJSON(
  deleteFileRequest: DeleteFileRequest,
): string {
  return JSON.stringify(
    DeleteFileRequest$outboundSchema.parse(deleteFileRequest),
  );
}
