/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteSeriesRequest = {
  /**
   * UUID of the series to delete
   */
  seriesId: string;
};

/** @internal */
export type DeleteSeriesRequest$Outbound = {
  series_id: string;
};

/** @internal */
export const DeleteSeriesRequest$outboundSchema: z.ZodType<
  DeleteSeriesRequest$Outbound,
  z.ZodTypeDef,
  DeleteSeriesRequest
> = z.object({
  seriesId: z.string(),
}).transform((v) => {
  return remap$(v, {
    seriesId: "series_id",
  });
});

export function deleteSeriesRequestToJSON(
  deleteSeriesRequest: DeleteSeriesRequest,
): string {
  return JSON.stringify(
    DeleteSeriesRequest$outboundSchema.parse(deleteSeriesRequest),
  );
}
