/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeletePostRequest = {
  /**
   * UUID of the post to delete
   */
  postId: string;
};

/** @internal */
export type DeletePostRequest$Outbound = {
  post_id: string;
};

/** @internal */
export const DeletePostRequest$outboundSchema: z.ZodType<
  DeletePostRequest$Outbound,
  z.ZodTypeDef,
  DeletePostRequest
> = z.object({
  postId: z.string(),
}).transform((v) => {
  return remap$(v, {
    postId: "post_id",
  });
});

export function deletePostRequestToJSON(
  deletePostRequest: DeletePostRequest,
): string {
  return JSON.stringify(
    DeletePostRequest$outboundSchema.parse(deletePostRequest),
  );
}
