/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteApiKeyRequest = {
  /**
   * UUID of the API key to delete
   */
  apiKeyId: string;
};

/** @internal */
export type DeleteApiKeyRequest$Outbound = {
  api_key_id: string;
};

/** @internal */
export const DeleteApiKeyRequest$outboundSchema: z.ZodType<
  DeleteApiKeyRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiKeyRequest
> = z.object({
  apiKeyId: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiKeyId: "api_key_id",
  });
});

export function deleteApiKeyRequestToJSON(
  deleteApiKeyRequest: DeleteApiKeyRequest,
): string {
  return JSON.stringify(
    DeleteApiKeyRequest$outboundSchema.parse(deleteApiKeyRequest),
  );
}
