/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetApiKeyRequest = {
  /**
   * UUID of the API key to retrieve
   */
  apiKeyId: string;
};

/** @internal */
export type GetApiKeyRequest$Outbound = {
  api_key_id: string;
};

/** @internal */
export const GetApiKeyRequest$outboundSchema: z.ZodType<
  GetApiKeyRequest$Outbound,
  z.ZodTypeDef,
  GetApiKeyRequest
> = z.object({
  apiKeyId: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiKeyId: "api_key_id",
  });
});

export function getApiKeyRequestToJSON(
  getApiKeyRequest: GetApiKeyRequest,
): string {
  return JSON.stringify(
    GetApiKeyRequest$outboundSchema.parse(getApiKeyRequest),
  );
}
