/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetFileRequest = {
  /**
   * UUID of the file to retrieve details for
   */
  fileId: string;
};

/** @internal */
export type GetFileRequest$Outbound = {
  file_id: string;
};

/** @internal */
export const GetFileRequest$outboundSchema: z.ZodType<
  GetFileRequest$Outbound,
  z.ZodTypeDef,
  GetFileRequest
> = z.object({
  fileId: z.string(),
}).transform((v) => {
  return remap$(v, {
    fileId: "file_id",
  });
});

export function getFileRequestToJSON(getFileRequest: GetFileRequest): string {
  return JSON.stringify(GetFileRequest$outboundSchema.parse(getFileRequest));
}
