/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPostRequest = {
  /**
   * UUID of the post to retrieve
   */
  postId: string;
};

/** @internal */
export type GetPostRequest$Outbound = {
  post_id: string;
};

/** @internal */
export const GetPostRequest$outboundSchema: z.ZodType<
  GetPostRequest$Outbound,
  z.ZodTypeDef,
  GetPostRequest
> = z.object({
  postId: z.string(),
}).transform((v) => {
  return remap$(v, {
    postId: "post_id",
  });
});

export function getPostRequestToJSON(getPostRequest: GetPostRequest): string {
  return JSON.stringify(GetPostRequest$outboundSchema.parse(getPostRequest));
}
