/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetSeriesRequest = {
  /**
   * UUID of the series to retrieve
   */
  seriesId: string;
};

/** @internal */
export type GetSeriesRequest$Outbound = {
  series_id: string;
};

/** @internal */
export const GetSeriesRequest$outboundSchema: z.ZodType<
  GetSeriesRequest$Outbound,
  z.ZodTypeDef,
  GetSeriesRequest
> = z.object({
  seriesId: z.string(),
}).transform((v) => {
  return remap$(v, {
    seriesId: "series_id",
  });
});

export function getSeriesRequestToJSON(
  getSeriesRequest: GetSeriesRequest,
): string {
  return JSON.stringify(
    GetSeriesRequest$outboundSchema.parse(getSeriesRequest),
  );
}
