/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GoogleAuthCallbackRequest = {
  /**
   * Authorization code from Google
   */
  code: string;
  /**
   * State parameter for CSRF protection
   */
  state: string;
};

/** @internal */
export type GoogleAuthCallbackRequest$Outbound = {
  code: string;
  state: string;
};

/** @internal */
export const GoogleAuthCallbackRequest$outboundSchema: z.ZodType<
  GoogleAuthCallbackRequest$Outbound,
  z.ZodTypeDef,
  GoogleAuthCallbackRequest
> = z.object({
  code: z.string(),
  state: z.string(),
});

export function googleAuthCallbackRequestToJSON(
  googleAuthCallbackRequest: GoogleAuthCallbackRequest,
): string {
  return JSON.stringify(
    GoogleAuthCallbackRequest$outboundSchema.parse(googleAuthCallbackRequest),
  );
}
