/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListPostsRequest = {
  /**
   * UUID offset for cursor-based posts pagination
   */
  offset?: string | null | undefined;
  /**
   * Maximum number of posts to return (default: 50, max: 100)
   */
  limit?: number | null | undefined;
  /**
   * Filter posts by series ID
   */
  seriesId?: string | null | undefined;
};

/** @internal */
export const ListPostsRequest$inboundSchema: z.ZodType<
  ListPostsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  offset: z.nullable(z.string()).optional(),
  limit: z.nullable(z.number().int()).optional(),
  series_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "series_id": "seriesId",
  });
});

/** @internal */
export type ListPostsRequest$Outbound = {
  offset?: string | null | undefined;
  limit?: number | null | undefined;
  series_id?: string | null | undefined;
};

/** @internal */
export const ListPostsRequest$outboundSchema: z.ZodType<
  ListPostsRequest$Outbound,
  z.ZodTypeDef,
  ListPostsRequest
> = z.object({
  offset: z.nullable(z.string()).optional(),
  limit: z.nullable(z.number().int()).optional(),
  seriesId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    seriesId: "series_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPostsRequest$ {
  /** @deprecated use `ListPostsRequest$inboundSchema` instead. */
  export const inboundSchema = ListPostsRequest$inboundSchema;
  /** @deprecated use `ListPostsRequest$outboundSchema` instead. */
  export const outboundSchema = ListPostsRequest$outboundSchema;
  /** @deprecated use `ListPostsRequest$Outbound` instead. */
  export type Outbound = ListPostsRequest$Outbound;
}

export function listPostsRequestToJSON(
  listPostsRequest: ListPostsRequest,
): string {
  return JSON.stringify(
    ListPostsRequest$outboundSchema.parse(listPostsRequest),
  );
}

export function listPostsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListPostsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPostsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPostsRequest' from JSON`,
  );
}
