/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListFilesRequest = {
  /**
   * UUID offset for cursor-based files pagination
   */
  offset?: string | null | undefined;
  /**
   * Maximum number of files to return (default: 50, max: 100)
   */
  limit?: number | null | undefined;
};

/** @internal */
export type ListFilesRequest$Outbound = {
  offset?: string | null | undefined;
  limit?: number | null | undefined;
};

/** @internal */
export const ListFilesRequest$outboundSchema: z.ZodType<
  ListFilesRequest$Outbound,
  z.ZodTypeDef,
  ListFilesRequest
> = z.object({
  offset: z.nullable(z.string()).optional(),
  limit: z.nullable(z.number().int()).optional(),
});

export function listFilesRequestToJSON(
  listFilesRequest: ListFilesRequest,
): string {
  return JSON.stringify(
    ListFilesRequest$outboundSchema.parse(listFilesRequest),
  );
}
