/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListPostsRequest = {
  /**
   * UUID offset for cursor-based posts pagination
   */
  offset?: string | null | undefined;
  /**
   * Maximum number of posts to return (default: 50, max: 100)
   */
  limit?: number | null | undefined;
  /**
   * Filter posts by series ID
   */
  seriesId?: string | null | undefined;
};

export type ListPostsResponse = {
  result: Array<models.PostResponse>;
};

/** @internal */
export type ListPostsRequest$Outbound = {
  offset?: string | null | undefined;
  limit?: number | null | undefined;
  series_id?: string | null | undefined;
};

/** @internal */
export const ListPostsRequest$outboundSchema: z.ZodType<
  ListPostsRequest$Outbound,
  z.ZodTypeDef,
  ListPostsRequest
> = z.object({
  offset: z.nullable(z.string()).optional(),
  limit: z.nullable(z.number().int()).optional(),
  seriesId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    seriesId: "series_id",
  });
});

export function listPostsRequestToJSON(
  listPostsRequest: ListPostsRequest,
): string {
  return JSON.stringify(
    ListPostsRequest$outboundSchema.parse(listPostsRequest),
  );
}

/** @internal */
export const ListPostsResponse$inboundSchema: z.ZodType<
  ListPostsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.array(models.PostResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listPostsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPostsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPostsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPostsResponse' from JSON`,
  );
}
