/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListApiKeysRequest = {
  /**
   * Starting point UUID for paginated API key results
   */
  offset?: string | null | undefined;
  /**
   * Number of API keys to return per page (default: 50, max: 100)
   */
  limit?: number | null | undefined;
  /**
   * Only show active or inactive API keys
   */
  isActive?: boolean | null | undefined;
};

export type ListApiKeysResponse = {
  result: Array<models.ApiKeyResponse>;
};

/** @internal */
export type ListApiKeysRequest$Outbound = {
  offset?: string | null | undefined;
  limit?: number | null | undefined;
  isActive?: boolean | null | undefined;
};

/** @internal */
export const ListApiKeysRequest$outboundSchema: z.ZodType<
  ListApiKeysRequest$Outbound,
  z.ZodTypeDef,
  ListApiKeysRequest
> = z.object({
  offset: z.nullable(z.string()).optional(),
  limit: z.nullable(z.number().int()).optional(),
  isActive: z.nullable(z.boolean()).optional(),
});

export function listApiKeysRequestToJSON(
  listApiKeysRequest: ListApiKeysRequest,
): string {
  return JSON.stringify(
    ListApiKeysRequest$outboundSchema.parse(listApiKeysRequest),
  );
}

/** @internal */
export const ListApiKeysResponse$inboundSchema: z.ZodType<
  ListApiKeysResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.array(models.ApiKeyResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listApiKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiKeysResponse' from JSON`,
  );
}
