/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListSeriesRequest = {
  /**
   * UUID offset for cursor-based series pagination
   */
  offset?: string | null | undefined;
  /**
   * Maximum number of series to return (default: 50, max: 100)
   */
  limit?: number | null | undefined;
};

export type ListSeriesResponse = {
  result: Array<models.SeriesResponse>;
};

/** @internal */
export type ListSeriesRequest$Outbound = {
  offset?: string | null | undefined;
  limit?: number | null | undefined;
};

/** @internal */
export const ListSeriesRequest$outboundSchema: z.ZodType<
  ListSeriesRequest$Outbound,
  z.ZodTypeDef,
  ListSeriesRequest
> = z.object({
  offset: z.nullable(z.string()).optional(),
  limit: z.nullable(z.number().int()).optional(),
});

export function listSeriesRequestToJSON(
  listSeriesRequest: ListSeriesRequest,
): string {
  return JSON.stringify(
    ListSeriesRequest$outboundSchema.parse(listSeriesRequest),
  );
}

/** @internal */
export const ListSeriesResponse$inboundSchema: z.ZodType<
  ListSeriesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.array(models.SeriesResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listSeriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSeriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSeriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeriesResponse' from JSON`,
  );
}
