/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ProcessWebhookSecurity = {
  bearerAuth: string;
};

/** @internal */
export type ProcessWebhookSecurity$Outbound = {
  bearerAuth: string;
};

/** @internal */
export const ProcessWebhookSecurity$outboundSchema: z.ZodType<
  ProcessWebhookSecurity$Outbound,
  z.ZodTypeDef,
  ProcessWebhookSecurity
> = z.object({
  bearerAuth: z.string(),
});

export function processWebhookSecurityToJSON(
  processWebhookSecurity: ProcessWebhookSecurity,
): string {
  return JSON.stringify(
    ProcessWebhookSecurity$outboundSchema.parse(processWebhookSecurity),
  );
}
