/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ServeFileCdnRequest = {
  /**
   * UUID of the file to stream via CDN
   */
  fileId: string;
};

/** @internal */
export type ServeFileCdnRequest$Outbound = {
  file_id: string;
};

/** @internal */
export const ServeFileCdnRequest$outboundSchema: z.ZodType<
  ServeFileCdnRequest$Outbound,
  z.ZodTypeDef,
  ServeFileCdnRequest
> = z.object({
  fileId: z.string(),
}).transform((v) => {
  return remap$(v, {
    fileId: "file_id",
  });
});

export function serveFileCdnRequestToJSON(
  serveFileCdnRequest: ServeFileCdnRequest,
): string {
  return JSON.stringify(
    ServeFileCdnRequest$outboundSchema.parse(serveFileCdnRequest),
  );
}
