/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServeFileCdnSecurity = {
  cookieAuth: string;
};

export type ServeFileCdnRequest = {
  /**
   * UUID of the file to stream via CDN
   */
  fileId: string;
};

/** @internal */
export const ServeFileCdnSecurity$inboundSchema: z.ZodType<
  ServeFileCdnSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  cookieAuth: z.string(),
});

/** @internal */
export type ServeFileCdnSecurity$Outbound = {
  cookieAuth: string;
};

/** @internal */
export const ServeFileCdnSecurity$outboundSchema: z.ZodType<
  ServeFileCdnSecurity$Outbound,
  z.ZodTypeDef,
  ServeFileCdnSecurity
> = z.object({
  cookieAuth: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServeFileCdnSecurity$ {
  /** @deprecated use `ServeFileCdnSecurity$inboundSchema` instead. */
  export const inboundSchema = ServeFileCdnSecurity$inboundSchema;
  /** @deprecated use `ServeFileCdnSecurity$outboundSchema` instead. */
  export const outboundSchema = ServeFileCdnSecurity$outboundSchema;
  /** @deprecated use `ServeFileCdnSecurity$Outbound` instead. */
  export type Outbound = ServeFileCdnSecurity$Outbound;
}

export function serveFileCdnSecurityToJSON(
  serveFileCdnSecurity: ServeFileCdnSecurity,
): string {
  return JSON.stringify(
    ServeFileCdnSecurity$outboundSchema.parse(serveFileCdnSecurity),
  );
}

export function serveFileCdnSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ServeFileCdnSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServeFileCdnSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServeFileCdnSecurity' from JSON`,
  );
}

/** @internal */
export const ServeFileCdnRequest$inboundSchema: z.ZodType<
  ServeFileCdnRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  file_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "file_id": "fileId",
  });
});

/** @internal */
export type ServeFileCdnRequest$Outbound = {
  file_id: string;
};

/** @internal */
export const ServeFileCdnRequest$outboundSchema: z.ZodType<
  ServeFileCdnRequest$Outbound,
  z.ZodTypeDef,
  ServeFileCdnRequest
> = z.object({
  fileId: z.string(),
}).transform((v) => {
  return remap$(v, {
    fileId: "file_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServeFileCdnRequest$ {
  /** @deprecated use `ServeFileCdnRequest$inboundSchema` instead. */
  export const inboundSchema = ServeFileCdnRequest$inboundSchema;
  /** @deprecated use `ServeFileCdnRequest$outboundSchema` instead. */
  export const outboundSchema = ServeFileCdnRequest$outboundSchema;
  /** @deprecated use `ServeFileCdnRequest$Outbound` instead. */
  export type Outbound = ServeFileCdnRequest$Outbound;
}

export function serveFileCdnRequestToJSON(
  serveFileCdnRequest: ServeFileCdnRequest,
): string {
  return JSON.stringify(
    ServeFileCdnRequest$outboundSchema.parse(serveFileCdnRequest),
  );
}

export function serveFileCdnRequestFromJSON(
  jsonString: string,
): SafeParseResult<ServeFileCdnRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServeFileCdnRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServeFileCdnRequest' from JSON`,
  );
}
