/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdatePostRequest = {
  /**
   * UUID of the post to update
   */
  postId: string;
  /**
   * Updated post data
   */
  updatePostRequest: models.UpdatePostRequest;
};

/** @internal */
export type UpdatePostRequest$Outbound = {
  post_id: string;
  UpdatePostRequest: models.UpdatePostRequest$Outbound;
};

/** @internal */
export const UpdatePostRequest$outboundSchema: z.ZodType<
  UpdatePostRequest$Outbound,
  z.ZodTypeDef,
  UpdatePostRequest
> = z.object({
  postId: z.string(),
  updatePostRequest: models.UpdatePostRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    postId: "post_id",
    updatePostRequest: "UpdatePostRequest",
  });
});

export function updatePostRequestToJSON(
  updatePostRequest: UpdatePostRequest,
): string {
  return JSON.stringify(
    UpdatePostRequest$outboundSchema.parse(updatePostRequest),
  );
}
