/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateSeriesRequest = {
  /**
   * UUID of the series to update
   */
  seriesId: string;
  /**
   * Updated series data
   */
  updateSeriesRequest: models.UpdateSeriesRequest;
};

/** @internal */
export type UpdateSeriesRequest$Outbound = {
  series_id: string;
  UpdateSeriesRequest: models.UpdateSeriesRequest$Outbound;
};

/** @internal */
export const UpdateSeriesRequest$outboundSchema: z.ZodType<
  UpdateSeriesRequest$Outbound,
  z.ZodTypeDef,
  UpdateSeriesRequest
> = z.object({
  seriesId: z.string(),
  updateSeriesRequest: models.UpdateSeriesRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    seriesId: "series_id",
    updateSeriesRequest: "UpdateSeriesRequest",
  });
});

export function updateSeriesRequestToJSON(
  updateSeriesRequest: UpdateSeriesRequest,
): string {
  return JSON.stringify(
    UpdateSeriesRequest$outboundSchema.parse(updateSeriesRequest),
  );
}
