/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateFileRequest = {
  /**
   * UUID of the file to update metadata for
   */
  fileId: string;
  /**
   * Updated file metadata, filename, or status
   */
  updateUserFileRequest: models.UpdateUserFileRequest;
};

/** @internal */
export type UpdateFileRequest$Outbound = {
  file_id: string;
  UpdateUserFileRequest: models.UpdateUserFileRequest$Outbound;
};

/** @internal */
export const UpdateFileRequest$outboundSchema: z.ZodType<
  UpdateFileRequest$Outbound,
  z.ZodTypeDef,
  UpdateFileRequest
> = z.object({
  fileId: z.string(),
  updateUserFileRequest: models.UpdateUserFileRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    fileId: "file_id",
    updateUserFileRequest: "UpdateUserFileRequest",
  });
});

export function updateFileRequestToJSON(
  updateFileRequest: UpdateFileRequest,
): string {
  return JSON.stringify(
    UpdateFileRequest$outboundSchema.parse(updateFileRequest),
  );
}
