/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateApiKeyRequest = {
  /**
   * UUID of the API key to update
   */
  apiKeyId: string;
  /**
   * Updated API key data
   */
  updateApiKeyRequest: models.UpdateApiKeyRequest;
};

/** @internal */
export type UpdateApiKeyRequest$Outbound = {
  api_key_id: string;
  UpdateApiKeyRequest: models.UpdateApiKeyRequest$Outbound;
};

/** @internal */
export const UpdateApiKeyRequest$outboundSchema: z.ZodType<
  UpdateApiKeyRequest$Outbound,
  z.ZodTypeDef,
  UpdateApiKeyRequest
> = z.object({
  apiKeyId: z.string(),
  updateApiKeyRequest: models.UpdateApiKeyRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    apiKeyId: "api_key_id",
    updateApiKeyRequest: "UpdateApiKeyRequest",
  });
});

export function updateApiKeyRequestToJSON(
  updateApiKeyRequest: UpdateApiKeyRequest,
): string {
  return JSON.stringify(
    UpdateApiKeyRequest$outboundSchema.parse(updateApiKeyRequest),
  );
}
