/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type VerifyEmailRequest = {
  /**
   * Email verification token
   */
  token: string;
};

/** @internal */
export type VerifyEmailRequest$Outbound = {
  token: string;
};

/** @internal */
export const VerifyEmailRequest$outboundSchema: z.ZodType<
  VerifyEmailRequest$Outbound,
  z.ZodTypeDef,
  VerifyEmailRequest
> = z.object({
  token: z.string(),
});

export function verifyEmailRequestToJSON(
  verifyEmailRequest: VerifyEmailRequest,
): string {
  return JSON.stringify(
    VerifyEmailRequest$outboundSchema.parse(verifyEmailRequest),
  );
}
