/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type VerifyEmailRequest = {
  /**
   * Email verification token
   */
  token: string;
};

/** @internal */
export const VerifyEmailRequest$inboundSchema: z.ZodType<
  VerifyEmailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string(),
});

/** @internal */
export type VerifyEmailRequest$Outbound = {
  token: string;
};

/** @internal */
export const VerifyEmailRequest$outboundSchema: z.ZodType<
  VerifyEmailRequest$Outbound,
  z.ZodTypeDef,
  VerifyEmailRequest
> = z.object({
  token: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VerifyEmailRequest$ {
  /** @deprecated use `VerifyEmailRequest$inboundSchema` instead. */
  export const inboundSchema = VerifyEmailRequest$inboundSchema;
  /** @deprecated use `VerifyEmailRequest$outboundSchema` instead. */
  export const outboundSchema = VerifyEmailRequest$outboundSchema;
  /** @deprecated use `VerifyEmailRequest$Outbound` instead. */
  export type Outbound = VerifyEmailRequest$Outbound;
}

export function verifyEmailRequestToJSON(
  verifyEmailRequest: VerifyEmailRequest,
): string {
  return JSON.stringify(
    VerifyEmailRequest$outboundSchema.parse(verifyEmailRequest),
  );
}

export function verifyEmailRequestFromJSON(
  jsonString: string,
): SafeParseResult<VerifyEmailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerifyEmailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerifyEmailRequest' from JSON`,
  );
}
