/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Authentication provider types supported by the system
 */
export const AuthProvider = {
  Google: "google",
  Email: "email",
  Both: "both",
} as const;
/**
 * Authentication provider types supported by the system
 */
export type AuthProvider = ClosedEnum<typeof AuthProvider>;

/** @internal */
export const AuthProvider$inboundSchema: z.ZodNativeEnum<typeof AuthProvider> =
  z.nativeEnum(AuthProvider);
