/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Authentication provider types supported by the system
 */
export const AuthProvider = {
  Google: "google",
  Email: "email",
  Both: "both",
} as const;
/**
 * Authentication provider types supported by the system
 */
export type AuthProvider = ClosedEnum<typeof AuthProvider>;

/** @internal */
export const AuthProvider$inboundSchema: z.ZodNativeEnum<typeof AuthProvider> =
  z.nativeEnum(AuthProvider);

/** @internal */
export const AuthProvider$outboundSchema: z.ZodNativeEnum<typeof AuthProvider> =
  AuthProvider$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthProvider$ {
  /** @deprecated use `AuthProvider$inboundSchema` instead. */
  export const inboundSchema = AuthProvider$inboundSchema;
  /** @deprecated use `AuthProvider$outboundSchema` instead. */
  export const outboundSchema = AuthProvider$outboundSchema;
}
