/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request body for checking if email exists
 */
export type CheckEmailRequest = {
  /**
   * Email address to check
   */
  email: string;
};

/** @internal */
export type CheckEmailRequest$Outbound = {
  email: string;
};

/** @internal */
export const CheckEmailRequest$outboundSchema: z.ZodType<
  CheckEmailRequest$Outbound,
  z.ZodTypeDef,
  CheckEmailRequest
> = z.object({
  email: z.string(),
});

export function checkEmailRequestToJSON(
  checkEmailRequest: CheckEmailRequest,
): string {
  return JSON.stringify(
    CheckEmailRequest$outboundSchema.parse(checkEmailRequest),
  );
}
