/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request payload for creating a new series with content and metadata
 */
export type CreateSeriesRequest = {
  /**
   * Category or genre of the series (optional)
   */
  category?: string | null | undefined;
  /**
   * Banner image URL for the series homepage
   */
  coverImageUrl?: string | null | undefined;
  /**
   * Description of the series content and purpose (optional)
   */
  description?: string | null | undefined;
  /**
   * Unique URL path segment for the new series
   */
  slug: string;
  /**
   * Name for the new series being created
   */
  title: string;
};

/** @internal */
export type CreateSeriesRequest$Outbound = {
  category?: string | null | undefined;
  coverImageUrl?: string | null | undefined;
  description?: string | null | undefined;
  slug: string;
  title: string;
};

/** @internal */
export const CreateSeriesRequest$outboundSchema: z.ZodType<
  CreateSeriesRequest$Outbound,
  z.ZodTypeDef,
  CreateSeriesRequest
> = z.object({
  category: z.nullable(z.string()).optional(),
  coverImageUrl: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  slug: z.string(),
  title: z.string(),
});

export function createSeriesRequestToJSON(
  createSeriesRequest: CreateSeriesRequest,
): string {
  return JSON.stringify(
    CreateSeriesRequest$outboundSchema.parse(createSeriesRequest),
  );
}
