/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request payload for creating a new API key
 */
export type CreateApiKeyRequest = {
  /**
   * When the API key should expire (optional)
   */
  expiresAt?: Date | null | undefined;
  /**
   * Name identifier for the new API key
   */
  name: string;
  /**
   * Array of permissions to grant to this key
   */
  permissions?: Array<string> | null | undefined;
};

/** @internal */
export type CreateApiKeyRequest$Outbound = {
  expiresAt?: string | null | undefined;
  name: string;
  permissions?: Array<string> | null | undefined;
};

/** @internal */
export const CreateApiKeyRequest$outboundSchema: z.ZodType<
  CreateApiKeyRequest$Outbound,
  z.ZodTypeDef,
  CreateApiKeyRequest
> = z.object({
  expiresAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  name: z.string(),
  permissions: z.nullable(z.array(z.string())).optional(),
});

export function createApiKeyRequestToJSON(
  createApiKeyRequest: CreateApiKeyRequest,
): string {
  return JSON.stringify(
    CreateApiKeyRequest$outboundSchema.parse(createApiKeyRequest),
  );
}
