/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response when creating a new API key - includes the actual key value
 */
export type CreateApiKeyResponse = {
  /**
   * Timestamp of when the API key was just created
   */
  createdAt?: Date | null | undefined;
  /**
   * Key expiration date (when provided)
   */
  expiresAt?: Date | null | undefined;
  /**
   * UUID of the newly created API key
   */
  id: string;
  /**
   * Initial active status of the new API key
   */
  isActive: boolean;
  /**
   * The actual API key value (only shown once during creation)
   */
  key: string;
  /**
   * Prefix portion of the newly generated key
   */
  keyPrefix: string;
  /**
   * Display name shown for this API key
   */
  name: string;
  /**
   * Permissions assigned to the new API key
   */
  permissions: Array<string>;
};

/** @internal */
export const CreateApiKeyResponse$inboundSchema: z.ZodType<
  CreateApiKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  expiresAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  id: z.string(),
  isActive: z.boolean(),
  key: z.string(),
  keyPrefix: z.string(),
  name: z.string(),
  permissions: z.array(z.string()),
});

export function createApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKeyResponse' from JSON`,
  );
}
