/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { blobLikeSchema } from "../types/blobs.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/**
 * File upload request schema for multipart form data
 */
export type FileUploadRequest = {
  /**
   * The file to upload
   */
  file: FileT | Blob;
};

/** @internal */
export const FileT$inboundSchema: z.ZodType<FileT, z.ZodTypeDef, unknown> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodType<
  FileT$Outbound,
  z.ZodTypeDef,
  FileT
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileT$ {
  /** @deprecated use `FileT$inboundSchema` instead. */
  export const inboundSchema = FileT$inboundSchema;
  /** @deprecated use `FileT$outboundSchema` instead. */
  export const outboundSchema = FileT$outboundSchema;
  /** @deprecated use `FileT$Outbound` instead. */
  export type Outbound = FileT$Outbound;
}

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

export function fileFromJSON(
  jsonString: string,
): SafeParseResult<FileT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileT' from JSON`,
  );
}

/** @internal */
export const FileUploadRequest$inboundSchema: z.ZodType<
  FileUploadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  file: z.lazy(() => FileT$inboundSchema),
});

/** @internal */
export type FileUploadRequest$Outbound = {
  file: FileT$Outbound | Blob;
};

/** @internal */
export const FileUploadRequest$outboundSchema: z.ZodType<
  FileUploadRequest$Outbound,
  z.ZodTypeDef,
  FileUploadRequest
> = z.object({
  file: z.lazy(() => FileT$outboundSchema).or(blobLikeSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileUploadRequest$ {
  /** @deprecated use `FileUploadRequest$inboundSchema` instead. */
  export const inboundSchema = FileUploadRequest$inboundSchema;
  /** @deprecated use `FileUploadRequest$outboundSchema` instead. */
  export const outboundSchema = FileUploadRequest$outboundSchema;
  /** @deprecated use `FileUploadRequest$Outbound` instead. */
  export type Outbound = FileUploadRequest$Outbound;
}

export function fileUploadRequestToJSON(
  fileUploadRequest: FileUploadRequest,
): string {
  return JSON.stringify(
    FileUploadRequest$outboundSchema.parse(fileUploadRequest),
  );
}

export function fileUploadRequestFromJSON(
  jsonString: string,
): SafeParseResult<FileUploadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileUploadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileUploadRequest' from JSON`,
  );
}
