/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { UserFileInfo, UserFileInfo$inboundSchema } from "./userfileinfo.js";

/**
 * Response for file upload operations
 */
export type FileUploadResponse = {
  /**
   * User file information for API responses
   */
  file: UserFileInfo;
  /**
   * Upload confirmation message
   */
  message: string;
};

/** @internal */
export const FileUploadResponse$inboundSchema: z.ZodType<
  FileUploadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  file: UserFileInfo$inboundSchema,
  message: z.string(),
});

export function fileUploadResponseFromJSON(
  jsonString: string,
): SafeParseResult<FileUploadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileUploadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileUploadResponse' from JSON`,
  );
}
