/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { blobLikeSchema } from "../types/blobs.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/**
 * File upload request schema for multipart form data
 */
export type FileUploadRequest = {
  /**
   * The file to upload
   */
  file: FileT | Blob;
};

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodType<
  FileT$Outbound,
  z.ZodTypeDef,
  FileT
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

/** @internal */
export type FileUploadRequest$Outbound = {
  file: FileT$Outbound | Blob;
};

/** @internal */
export const FileUploadRequest$outboundSchema: z.ZodType<
  FileUploadRequest$Outbound,
  z.ZodTypeDef,
  FileUploadRequest
> = z.object({
  file: z.lazy(() => FileT$outboundSchema).or(blobLikeSchema),
});

export function fileUploadRequestToJSON(
  fileUploadRequest: FileUploadRequest,
): string {
  return JSON.stringify(
    FileUploadRequest$outboundSchema.parse(fileUploadRequest),
  );
}
