/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * File processing status for user uploaded files
 */
export const FileStatus = {
  Uploaded: "uploaded",
  Processing: "processing",
  Processed: "processed",
  Failed: "failed",
  Deleted: "deleted",
} as const;
/**
 * File processing status for user uploaded files
 */
export type FileStatus = ClosedEnum<typeof FileStatus>;

/** @internal */
export const FileStatus$inboundSchema: z.ZodNativeEnum<typeof FileStatus> = z
  .nativeEnum(FileStatus);

/** @internal */
export const FileStatus$outboundSchema: z.ZodNativeEnum<typeof FileStatus> =
  FileStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileStatus$ {
  /** @deprecated use `FileStatus$inboundSchema` instead. */
  export const inboundSchema = FileStatus$inboundSchema;
  /** @deprecated use `FileStatus$outboundSchema` instead. */
  export const outboundSchema = FileStatus$outboundSchema;
}
