/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response for password reset request
 */
export type ForgotPasswordResponse = {
  /**
   * Password reset request status message
   */
  message: string;
};

/** @internal */
export const ForgotPasswordResponse$inboundSchema: z.ZodType<
  ForgotPasswordResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

export function forgotPasswordResponseFromJSON(
  jsonString: string,
): SafeParseResult<ForgotPasswordResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForgotPasswordResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForgotPasswordResponse' from JSON`,
  );
}
