/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request body for password reset
 */
export type ForgotPasswordRequest = {
  /**
   * Email address to send password reset link to
   */
  email: string;
};

/** @internal */
export type ForgotPasswordRequest$Outbound = {
  email: string;
};

/** @internal */
export const ForgotPasswordRequest$outboundSchema: z.ZodType<
  ForgotPasswordRequest$Outbound,
  z.ZodTypeDef,
  ForgotPasswordRequest
> = z.object({
  email: z.string(),
});

export function forgotPasswordRequestToJSON(
  forgotPasswordRequest: ForgotPasswordRequest,
): string {
  return JSON.stringify(
    ForgotPasswordRequest$outboundSchema.parse(forgotPasswordRequest),
  );
}
