/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { UserInfo, UserInfo$inboundSchema } from "./userinfo.js";

/**
 * Response for successful user login
 */
export type LoginResponse = {
  /**
   * Login success message
   */
  message: string;
  /**
   * User information for API responses and internal use
   */
  user: UserInfo;
};

/** @internal */
export const LoginResponse$inboundSchema: z.ZodType<
  LoginResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  user: UserInfo$inboundSchema,
});

export function loginResponseFromJSON(
  jsonString: string,
): SafeParseResult<LoginResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginResponse' from JSON`,
  );
}
