/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request body for user login
 */
export type LoginRequest = {
  /**
   * Email address for login authentication
   */
  email: string;
  /**
   * User's password
   */
  password: string;
};

/** @internal */
export type LoginRequest$Outbound = {
  email: string;
  password: string;
};

/** @internal */
export const LoginRequest$outboundSchema: z.ZodType<
  LoginRequest$Outbound,
  z.ZodTypeDef,
  LoginRequest
> = z.object({
  email: z.string(),
  password: z.string(),
});

export function loginRequestToJSON(loginRequest: LoginRequest): string {
  return JSON.stringify(LoginRequest$outboundSchema.parse(loginRequest));
}
