/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response for successful logout
 */
export type LogoutResponse = {
  /**
   * Logout confirmation message
   */
  message: string;
};

/** @internal */
export const LogoutResponse$inboundSchema: z.ZodType<
  LogoutResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

export function logoutResponseFromJSON(
  jsonString: string,
): SafeParseResult<LogoutResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LogoutResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LogoutResponse' from JSON`,
  );
}
