/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response confirming webhook processing
 */
export type OutrankWebhookResponse = {
  /**
   * Success message
   */
  message: string;
};

/** @internal */
export const OutrankWebhookResponse$inboundSchema: z.ZodType<
  OutrankWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type OutrankWebhookResponse$Outbound = {
  message: string;
};

/** @internal */
export const OutrankWebhookResponse$outboundSchema: z.ZodType<
  OutrankWebhookResponse$Outbound,
  z.ZodTypeDef,
  OutrankWebhookResponse
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OutrankWebhookResponse$ {
  /** @deprecated use `OutrankWebhookResponse$inboundSchema` instead. */
  export const inboundSchema = OutrankWebhookResponse$inboundSchema;
  /** @deprecated use `OutrankWebhookResponse$outboundSchema` instead. */
  export const outboundSchema = OutrankWebhookResponse$outboundSchema;
  /** @deprecated use `OutrankWebhookResponse$Outbound` instead. */
  export type Outbound = OutrankWebhookResponse$Outbound;
}

export function outrankWebhookResponseToJSON(
  outrankWebhookResponse: OutrankWebhookResponse,
): string {
  return JSON.stringify(
    OutrankWebhookResponse$outboundSchema.parse(outrankWebhookResponse),
  );
}

export function outrankWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<OutrankWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutrankWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutrankWebhookResponse' from JSON`,
  );
}
