/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Webhook payload from Outrank SEO service
 */
export type OutrankWebhookPayload = {
  data?: { [k: string]: any } | null | undefined;
  /**
   * Event type from Outrank
   */
  eventType?: string | null | undefined;
};

/** @internal */
export type OutrankWebhookPayload$Outbound = {
  data?: { [k: string]: any } | null | undefined;
  eventType?: string | null | undefined;
};

/** @internal */
export const OutrankWebhookPayload$outboundSchema: z.ZodType<
  OutrankWebhookPayload$Outbound,
  z.ZodTypeDef,
  OutrankWebhookPayload
> = z.object({
  data: z.nullable(z.record(z.any())).optional(),
  eventType: z.nullable(z.string()).optional(),
});

export function outrankWebhookPayloadToJSON(
  outrankWebhookPayload: OutrankWebhookPayload,
): string {
  return JSON.stringify(
    OutrankWebhookPayload$outboundSchema.parse(outrankWebhookPayload),
  );
}
