/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response confirming webhook processing
 */
export type OutrankWebhookResponse = {
  /**
   * Success message
   */
  message: string;
};

/** @internal */
export const OutrankWebhookResponse$inboundSchema: z.ZodType<
  OutrankWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

export function outrankWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<OutrankWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutrankWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutrankWebhookResponse' from JSON`,
  );
}
