/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * API response model for posts
 */
export type PostResponse = {
  /**
   * ID of associated audio file
   */
  audioFileId?: string | null | undefined;
  /**
   * Post body text and content
   */
  content: string;
  /**
   * Post creation timestamp
   */
  createdAt?: Date | null | undefined;
  /**
   * Post's unique identifier
   */
  id: string;
  /**
   * Whether the post is published and visible to users
   */
  isPublished: boolean;
  /**
   * Position number for ordering this post within its parent series
   */
  postNumber: number;
  /**
   * Parent series identifier
   */
  seriesId: string;
  /**
   * SEO-friendly URL identifier for the post
   */
  slug: string;
  /**
   * URL to the post's thumbnail image
   */
  thumbnailUrl?: string | null | undefined;
  /**
   * Post display title
   */
  title: string;
  /**
   * Post last update timestamp
   */
  updatedAt?: Date | null | undefined;
  /**
   * ID of associated video file
   */
  videoFileId?: string | null | undefined;
};

/** @internal */
export const PostResponse$inboundSchema: z.ZodType<
  PostResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  audioFileId: z.nullable(z.string()).optional(),
  content: z.string(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  id: z.string(),
  isPublished: z.boolean(),
  postNumber: z.number().int(),
  seriesId: z.string(),
  slug: z.string(),
  thumbnailUrl: z.nullable(z.string()).optional(),
  title: z.string(),
  updatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  videoFileId: z.nullable(z.string()).optional(),
});

export function postResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostResponse' from JSON`,
  );
}
