/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { UserInfo, UserInfo$inboundSchema } from "./userinfo.js";

/**
 * Response for successful user registration
 */
export type RegisterResponse = {
  /**
   * Registration confirmation message
   */
  message: string;
  /**
   * User information for API responses and internal use
   */
  user: UserInfo;
};

/** @internal */
export const RegisterResponse$inboundSchema: z.ZodType<
  RegisterResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  user: UserInfo$inboundSchema,
});

export function registerResponseFromJSON(
  jsonString: string,
): SafeParseResult<RegisterResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegisterResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegisterResponse' from JSON`,
  );
}
