/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request body for user registration.
 */
export type RegisterRequest = {
  /**
   * Optional display name for the user
   */
  displayName?: string | null | undefined;
  /**
   * Email address for new user registration
   */
  email: string;
  /**
   * User's password (minimum 8 characters)
   */
  password: string;
};

/** @internal */
export type RegisterRequest$Outbound = {
  displayName?: string | null | undefined;
  email: string;
  password: string;
};

/** @internal */
export const RegisterRequest$outboundSchema: z.ZodType<
  RegisterRequest$Outbound,
  z.ZodTypeDef,
  RegisterRequest
> = z.object({
  displayName: z.nullable(z.string()).optional(),
  email: z.string(),
  password: z.string(),
});

export function registerRequestToJSON(
  registerRequest: RegisterRequest,
): string {
  return JSON.stringify(RegisterRequest$outboundSchema.parse(registerRequest));
}
