/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Request body for user registration.
 */
export type RegisterRequest = {
  /**
   * Optional display name for the user
   */
  displayName?: string | null | undefined;
  /**
   * Email address for new user registration
   */
  email: string;
  /**
   * User's password (minimum 8 characters)
   */
  password: string;
};

/** @internal */
export const RegisterRequest$inboundSchema: z.ZodType<
  RegisterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.nullable(z.string()).optional(),
  email: z.string(),
  password: z.string(),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
  });
});

/** @internal */
export type RegisterRequest$Outbound = {
  display_name?: string | null | undefined;
  email: string;
  password: string;
};

/** @internal */
export const RegisterRequest$outboundSchema: z.ZodType<
  RegisterRequest$Outbound,
  z.ZodTypeDef,
  RegisterRequest
> = z.object({
  displayName: z.nullable(z.string()).optional(),
  email: z.string(),
  password: z.string(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RegisterRequest$ {
  /** @deprecated use `RegisterRequest$inboundSchema` instead. */
  export const inboundSchema = RegisterRequest$inboundSchema;
  /** @deprecated use `RegisterRequest$outboundSchema` instead. */
  export const outboundSchema = RegisterRequest$outboundSchema;
  /** @deprecated use `RegisterRequest$Outbound` instead. */
  export type Outbound = RegisterRequest$Outbound;
}

export function registerRequestToJSON(
  registerRequest: RegisterRequest,
): string {
  return JSON.stringify(RegisterRequest$outboundSchema.parse(registerRequest));
}

export function registerRequestFromJSON(
  jsonString: string,
): SafeParseResult<RegisterRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegisterRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegisterRequest' from JSON`,
  );
}
