/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response for resend verification email request
 */
export type ResendVerificationResponse = {
  /**
   * Resend verification email status message
   */
  message: string;
};

/** @internal */
export const ResendVerificationResponse$inboundSchema: z.ZodType<
  ResendVerificationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type ResendVerificationResponse$Outbound = {
  message: string;
};

/** @internal */
export const ResendVerificationResponse$outboundSchema: z.ZodType<
  ResendVerificationResponse$Outbound,
  z.ZodTypeDef,
  ResendVerificationResponse
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResendVerificationResponse$ {
  /** @deprecated use `ResendVerificationResponse$inboundSchema` instead. */
  export const inboundSchema = ResendVerificationResponse$inboundSchema;
  /** @deprecated use `ResendVerificationResponse$outboundSchema` instead. */
  export const outboundSchema = ResendVerificationResponse$outboundSchema;
  /** @deprecated use `ResendVerificationResponse$Outbound` instead. */
  export type Outbound = ResendVerificationResponse$Outbound;
}

export function resendVerificationResponseToJSON(
  resendVerificationResponse: ResendVerificationResponse,
): string {
  return JSON.stringify(
    ResendVerificationResponse$outboundSchema.parse(resendVerificationResponse),
  );
}

export function resendVerificationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResendVerificationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResendVerificationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResendVerificationResponse' from JSON`,
  );
}
