/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response for successful password reset
 */
export type ResetPasswordResponse = {
  /**
   * Password reset confirmation message
   */
  message: string;
};

/** @internal */
export const ResetPasswordResponse$inboundSchema: z.ZodType<
  ResetPasswordResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

export function resetPasswordResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResetPasswordResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResetPasswordResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResetPasswordResponse' from JSON`,
  );
}
