/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response for resend verification email request
 */
export type ResendVerificationResponse = {
  /**
   * Resend verification email status message
   */
  message: string;
};

/** @internal */
export const ResendVerificationResponse$inboundSchema: z.ZodType<
  ResendVerificationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

export function resendVerificationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResendVerificationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResendVerificationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResendVerificationResponse' from JSON`,
  );
}
