/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request body for password reset confirmation
 */
export type ResetPasswordRequest = {
  /**
   * New password (minimum 8 characters)
   */
  newPassword: string;
  /**
   * Password reset token
   */
  token: string;
  /**
   * User ID associated with the reset token
   */
  userId: string;
};

/** @internal */
export type ResetPasswordRequest$Outbound = {
  newPassword: string;
  token: string;
  userId: string;
};

/** @internal */
export const ResetPasswordRequest$outboundSchema: z.ZodType<
  ResetPasswordRequest$Outbound,
  z.ZodTypeDef,
  ResetPasswordRequest
> = z.object({
  newPassword: z.string(),
  token: z.string(),
  userId: z.string(),
});

export function resetPasswordRequestToJSON(
  resetPasswordRequest: ResetPasswordRequest,
): string {
  return JSON.stringify(
    ResetPasswordRequest$outboundSchema.parse(resetPasswordRequest),
  );
}
