/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * API response model for series
 */
export type SeriesResponse = {
  /**
   * Category or genre of the series
   */
  category?: string | null | undefined;
  /**
   * URL to the series cover image
   */
  coverImageUrl?: string | null | undefined;
  /**
   * Series creation timestamp
   */
  createdAt?: Date | null | undefined;
  /**
   * Description of the series content and purpose
   */
  description?: string | null | undefined;
  /**
   * Series unique identifier
   */
  id: string;
  /**
   * Total number of posts in the series
   */
  length?: number | null | undefined;
  /**
   * SEO-friendly URL identifier for the series
   */
  slug: string;
  /**
   * Display name of the series
   */
  title: string;
  /**
   * Series last update timestamp
   */
  updatedAt?: Date | null | undefined;
  /**
   * ID of the user who owns this series
   */
  userId: string;
};

/** @internal */
export const SeriesResponse$inboundSchema: z.ZodType<
  SeriesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  category: z.nullable(z.string()).optional(),
  coverImageUrl: z.nullable(z.string()).optional(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  description: z.nullable(z.string()).optional(),
  id: z.string(),
  length: z.nullable(z.number().int()).optional(),
  slug: z.string(),
  title: z.string(),
  updatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  userId: z.string(),
});

export function seriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<SeriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SeriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SeriesResponse' from JSON`,
  );
}
