/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Request payload for updating series content, metadata, or status
 */
export type UpdateSeriesRequest = {
  /**
   * Updated category or genre of the series (optional)
   */
  category?: string | null | undefined;
  /**
   * Update the series banner image with a new URL
   */
  coverImageUrl?: string | null | undefined;
  /**
   * Updated description of the series (optional)
   */
  description?: string | null | undefined;
  /**
   * New URL-friendly slug for the series (optional)
   */
  slug?: string | null | undefined;
  /**
   * New title for the series (optional)
   */
  title?: string | null | undefined;
};

/** @internal */
export const UpdateSeriesRequest$inboundSchema: z.ZodType<
  UpdateSeriesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  category: z.nullable(z.string()).optional(),
  coverImageUrl: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  slug: z.nullable(z.string()).optional(),
  title: z.nullable(z.string()).optional(),
});

/** @internal */
export type UpdateSeriesRequest$Outbound = {
  category?: string | null | undefined;
  coverImageUrl?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  title?: string | null | undefined;
};

/** @internal */
export const UpdateSeriesRequest$outboundSchema: z.ZodType<
  UpdateSeriesRequest$Outbound,
  z.ZodTypeDef,
  UpdateSeriesRequest
> = z.object({
  category: z.nullable(z.string()).optional(),
  coverImageUrl: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  slug: z.nullable(z.string()).optional(),
  title: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateSeriesRequest$ {
  /** @deprecated use `UpdateSeriesRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateSeriesRequest$inboundSchema;
  /** @deprecated use `UpdateSeriesRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateSeriesRequest$outboundSchema;
  /** @deprecated use `UpdateSeriesRequest$Outbound` instead. */
  export type Outbound = UpdateSeriesRequest$Outbound;
}

export function updateSeriesRequestToJSON(
  updateSeriesRequest: UpdateSeriesRequest,
): string {
  return JSON.stringify(
    UpdateSeriesRequest$outboundSchema.parse(updateSeriesRequest),
  );
}

export function updateSeriesRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSeriesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSeriesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSeriesRequest' from JSON`,
  );
}
