/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { FileStatus, FileStatus$outboundSchema } from "./filestatus.js";

/**
 * Request payload for updating user file metadata, filename, or status
 */
export type UpdateUserFileRequest = {
  /**
   * New filename (optional)
   */
  filename?: string | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  status?: FileStatus | null | undefined;
};

/** @internal */
export type UpdateUserFileRequest$Outbound = {
  filename?: string | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  status?: string | null | undefined;
};

/** @internal */
export const UpdateUserFileRequest$outboundSchema: z.ZodType<
  UpdateUserFileRequest$Outbound,
  z.ZodTypeDef,
  UpdateUserFileRequest
> = z.object({
  filename: z.nullable(z.string()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  status: z.nullable(FileStatus$outboundSchema).optional(),
});

export function updateUserFileRequestToJSON(
  updateUserFileRequest: UpdateUserFileRequest,
): string {
  return JSON.stringify(
    UpdateUserFileRequest$outboundSchema.parse(updateUserFileRequest),
  );
}
