/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request payload for updating an API key
 */
export type UpdateApiKeyRequest = {
  /**
   * Update the expiration date
   */
  expiresAt?: Date | null | undefined;
  /**
   * Change the active status of the key
   */
  isActive?: boolean | null | undefined;
  /**
   * New name for the API key (optional)
   */
  name?: string | null | undefined;
  /**
   * Updated permissions array (optional)
   */
  permissions?: Array<string> | null | undefined;
};

/** @internal */
export type UpdateApiKeyRequest$Outbound = {
  expiresAt?: string | null | undefined;
  isActive?: boolean | null | undefined;
  name?: string | null | undefined;
  permissions?: Array<string> | null | undefined;
};

/** @internal */
export const UpdateApiKeyRequest$outboundSchema: z.ZodType<
  UpdateApiKeyRequest$Outbound,
  z.ZodTypeDef,
  UpdateApiKeyRequest
> = z.object({
  expiresAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  isActive: z.nullable(z.boolean()).optional(),
  name: z.nullable(z.string()).optional(),
  permissions: z.nullable(z.array(z.string())).optional(),
});

export function updateApiKeyRequestToJSON(
  updateApiKeyRequest: UpdateApiKeyRequest,
): string {
  return JSON.stringify(
    UpdateApiKeyRequest$outboundSchema.parse(updateApiKeyRequest),
  );
}
