/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request body for updating user information
 */
export type UpdateUserInfoRequest = {
  /**
   * Updated avatar URL for the user
   */
  avatarUrl?: string | null | undefined;
  /**
   * Updated banner URL for the user
   */
  banner?: string | null | undefined;
  /**
   * Updated description for the user
   */
  description?: string | null | undefined;
  /**
   * Updated display name for the user
   */
  displayName?: string | null | undefined;
};

/** @internal */
export type UpdateUserInfoRequest$Outbound = {
  avatarUrl?: string | null | undefined;
  banner?: string | null | undefined;
  description?: string | null | undefined;
  displayName?: string | null | undefined;
};

/** @internal */
export const UpdateUserInfoRequest$outboundSchema: z.ZodType<
  UpdateUserInfoRequest$Outbound,
  z.ZodTypeDef,
  UpdateUserInfoRequest
> = z.object({
  avatarUrl: z.nullable(z.string()).optional(),
  banner: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  displayName: z.nullable(z.string()).optional(),
});

export function updateUserInfoRequestToJSON(
  updateUserInfoRequest: UpdateUserInfoRequest,
): string {
  return JSON.stringify(
    UpdateUserInfoRequest$outboundSchema.parse(updateUserInfoRequest),
  );
}
