/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request payload for updating post content, metadata, or status
 */
export type UpdatePostRequest = {
  /**
   * Updated audio file reference for the post
   */
  audioFileId?: string | null | undefined;
  /**
   * Updated post content text (optional)
   */
  content?: string | null | undefined;
  /**
   * Change the publication visibility of this post
   */
  isPublished?: boolean | null | undefined;
  /**
   * Updated sequential number within the series (optional)
   */
  postNumber?: number | null | undefined;
  /**
   * New URL-friendly slug for the post (optional)
   */
  slug?: string | null | undefined;
  /**
   * Replace the post's cover image with a new URL
   */
  thumbnailUrl?: string | null | undefined;
  /**
   * New title for the post (optional)
   */
  title?: string | null | undefined;
  /**
   * Updated video file reference for the post
   */
  videoFileId?: string | null | undefined;
};

/** @internal */
export type UpdatePostRequest$Outbound = {
  audioFileId?: string | null | undefined;
  content?: string | null | undefined;
  isPublished?: boolean | null | undefined;
  postNumber?: number | null | undefined;
  slug?: string | null | undefined;
  thumbnailUrl?: string | null | undefined;
  title?: string | null | undefined;
  videoFileId?: string | null | undefined;
};

/** @internal */
export const UpdatePostRequest$outboundSchema: z.ZodType<
  UpdatePostRequest$Outbound,
  z.ZodTypeDef,
  UpdatePostRequest
> = z.object({
  audioFileId: z.nullable(z.string()).optional(),
  content: z.nullable(z.string()).optional(),
  isPublished: z.nullable(z.boolean()).optional(),
  postNumber: z.nullable(z.number().int()).optional(),
  slug: z.nullable(z.string()).optional(),
  thumbnailUrl: z.nullable(z.string()).optional(),
  title: z.nullable(z.string()).optional(),
  videoFileId: z.nullable(z.string()).optional(),
});

export function updatePostRequestToJSON(
  updatePostRequest: UpdatePostRequest,
): string {
  return JSON.stringify(
    UpdatePostRequest$outboundSchema.parse(updatePostRequest),
  );
}
