/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { FileStatus, FileStatus$inboundSchema } from "./filestatus.js";

/**
 * User file information for API responses
 */
export type UserFileInfo = {
  /**
   * File upload timestamp
   */
  createdAt?: Date | null | undefined;
  /**
   * SHA-256 hash of the file
   */
  fileHash: string;
  /**
   * Size of the file in bytes
   */
  fileSize: number;
  /**
   * Current filename
   */
  filename: string;
  /**
   * File's unique identifier
   */
  id: string;
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * MIME type of the file
   */
  mimeType: string;
  /**
   * Original filename as uploaded by user
   */
  originalFilename: string;
  /**
   * File processing status for user uploaded files
   */
  status: FileStatus;
  /**
   * File last update timestamp
   */
  updatedAt?: Date | null | undefined;
  /**
   * ID of the user who owns this file
   */
  userId: string;
};

/** @internal */
export const UserFileInfo$inboundSchema: z.ZodType<
  UserFileInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  fileHash: z.string(),
  fileSize: z.number().int(),
  filename: z.string(),
  id: z.string(),
  metadata: z.nullable(z.record(z.any())).optional(),
  mimeType: z.string(),
  originalFilename: z.string(),
  status: FileStatus$inboundSchema,
  updatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  userId: z.string(),
});

export function userFileInfoFromJSON(
  jsonString: string,
): SafeParseResult<UserFileInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserFileInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserFileInfo' from JSON`,
  );
}
