/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AuthProvider,
  AuthProvider$inboundSchema,
  AuthProvider$outboundSchema,
} from "./authprovider.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * User information for API responses and internal use
 */
export type UserInfo = {
  /**
   * Authentication provider types supported by the system
   */
  authProvider: AuthProvider;
  /**
   * URL to user's avatar image
   */
  avatarUrl?: string | null | undefined;
  /**
   * URL to user's banner image
   */
  banner?: string | null | undefined;
  /**
   * User account creation timestamp
   */
  createdAt?: Date | null | undefined;
  /**
   * User's description or bio
   */
  description?: string | null | undefined;
  /**
   * User's display name
   */
  displayName?: string | null | undefined;
  /**
   * User's registered email address
   */
  email: string;
  /**
   * Whether the user's email has been verified
   */
  emailVerified: boolean;
  /**
   * User's unique identifier
   */
  id: string;
  /**
   * Timestamp of user's last login
   */
  lastLogin?: Date | null | undefined;
};

/** @internal */
export const UserInfo$inboundSchema: z.ZodType<
  UserInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  authProvider: AuthProvider$inboundSchema,
  avatarUrl: z.nullable(z.string()).optional(),
  banner: z.nullable(z.string()).optional(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  description: z.nullable(z.string()).optional(),
  displayName: z.nullable(z.string()).optional(),
  email: z.string(),
  emailVerified: z.boolean(),
  id: z.string(),
  lastLogin: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});

/** @internal */
export type UserInfo$Outbound = {
  authProvider: string;
  avatarUrl?: string | null | undefined;
  banner?: string | null | undefined;
  createdAt?: string | null | undefined;
  description?: string | null | undefined;
  displayName?: string | null | undefined;
  email: string;
  emailVerified: boolean;
  id: string;
  lastLogin?: string | null | undefined;
};

/** @internal */
export const UserInfo$outboundSchema: z.ZodType<
  UserInfo$Outbound,
  z.ZodTypeDef,
  UserInfo
> = z.object({
  authProvider: AuthProvider$outboundSchema,
  avatarUrl: z.nullable(z.string()).optional(),
  banner: z.nullable(z.string()).optional(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  description: z.nullable(z.string()).optional(),
  displayName: z.nullable(z.string()).optional(),
  email: z.string(),
  emailVerified: z.boolean(),
  id: z.string(),
  lastLogin: z.nullable(z.date().transform(v => v.toISOString())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserInfo$ {
  /** @deprecated use `UserInfo$inboundSchema` instead. */
  export const inboundSchema = UserInfo$inboundSchema;
  /** @deprecated use `UserInfo$outboundSchema` instead. */
  export const outboundSchema = UserInfo$outboundSchema;
  /** @deprecated use `UserInfo$Outbound` instead. */
  export type Outbound = UserInfo$Outbound;
}

export function userInfoToJSON(userInfo: UserInfo): string {
  return JSON.stringify(UserInfo$outboundSchema.parse(userInfo));
}

export function userInfoFromJSON(
  jsonString: string,
): SafeParseResult<UserInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserInfo' from JSON`,
  );
}
