/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { PatrontsError } from "./patrontserror.js";

/**
 * Standard JSON error response structure for API endpoints.
 */
export type ErrorResponseData = {
  /**
   * Optional error code for programmatic handling
   */
  code?: string | null | undefined;
  /**
   * Error message describing what went wrong
   */
  error: string;
};

/**
 * Standard JSON error response structure for API endpoints.
 */
export class ErrorResponse extends PatrontsError {
  /**
   * Optional error code for programmatic handling
   */
  code?: string | null | undefined;
  /**
   * Error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: ErrorResponseData;

  constructor(
    err: ErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    this.error = err.error;

    this.name = "ErrorResponse";
  }
}

/** @internal */
export const ErrorResponse$inboundSchema: z.ZodType<
  ErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.nullable(z.string()).optional(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
