/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the patronts SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx apiKeysList.example.ts
 */

import { Patronts } from "patronts";

const patronts = new Patronts({
  security: {
    bearerAuth: process.env["PATRONTS_BEARER_AUTH"] ?? "",
    cookieAuth: process.env["PATRONTS_COOKIE_AUTH"] ?? "",
  },
});

async function main() {
  const result = await patronts.apiKeys.list();

  console.log(result);
}

main().catch(console.error);
