/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the patronts SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx authCheckEmail.example.ts
 */

import { Patronts } from "patronts";

const patronts = new Patronts({
  cookieAuth: process.env["PATRONTS_COOKIE_AUTH"] ?? "",
});

async function main() {
  await patronts.auth.checkEmail({
    email: "user@example.com",
  });
}

main().catch(console.error);
