/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the patronts SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx authForgotPassword.example.ts
 */

import { Patronts } from "patronts";

const patronts = new Patronts();

async function main() {
  const result = await patronts.forgotPassword({
    email: "user@example.com",
  });

  console.log(result);
}

main().catch(console.error);
